version: '3'

services:
  postgresdb:
    image: postgres:16-alpine
    container_name: simaku-elearning-db 
    ports:
      - 5432:5432
    volumes:
      - ~/_pg:/var/lib/postgresql/data
    environment:
       POSTGRES_USER: ${DB_USER}
       POSTGRES_PASSWORD: ${DB_PASSWORD}
       POSTGRES_DB: ${DB_NAME}
   
